ARG VERSION=20.04
# version is the name of the argument

FROM ubuntu:${VERSION}
# from provides the base images

RUN apt-get update -y
# run the commands using dockerfile
# this is where execution happens

CMD ["bash"]
# only run a specific command in the contianer

